# name: Kanagawa
# preferred_background: 1f1f28
# Based on https://github.com/rebelot/kanagawa.nvim/blob/master/extras/fish/kanagawa.fish

fish_color_normal dcd7ba
fish_color_command 7aa89f
fish_color_keyword d27e99
fish_color_quote c0a36e
fish_color_redirection dcd7ba
fish_color_end ff9e64
# fish_color_option 957fb8
fish_color_error c34043
fish_color_param 957fb8
fish_color_comment 727169
fish_color_selection --background=2d4f67
fish_color_search_match --background=2d4f67
fish_color_operator 76946a
fish_color_escape d27e99
fish_color_autosuggestion 727169
# fish_color_cancel c34043 --reverse
# fish_color_cwd 76946a
# fish_color_cwd_root c34043
# fish_color_host dcd7ba
# fish_color_host_remote c0a36e
# fish_color_user 7aa89f
# fish_color_status c34043
# fish_color_valid_path --underline
# fish_color_history_current --bold

fish_pager_color_progress 727169
# fish_pager_color_background --background=1f1f28
fish_pager_color_prefix 7aa89f
fish_pager_color_completion dcd7ba
fish_pager_color_description 727169
# fish_pager_color_selected_background --background=2d4f67
# fish_pager_color_selected_prefix 7aa89f --bold --underline --background=2d4f67
# fish_pager_color_selected_completion dcd7ba --background=2d4f67
# fish_pager_color_selected_description dcd7ba --background=2d4f67
# fish_pager_color_secondary_background --background=16161d
# fish_pager_color_secondary_prefix 6a9589 --background=16161d
# fish_pager_color_secondary_completion dcd7ba --background=16161d
# fish_pager_color_secondary_description 727169 --background=16161d
