# name: Monoglow
# preferred_background: 121212

fish_color_normal cccccc
fish_color_command 7bd88f
fish_color_keyword fc618d
fish_color_quote fce566
fish_color_redirection 5ad4e6
fish_color_end f1f1f1
fish_color_option 948ae3
fish_color_error fc618d
fish_color_param 9acbff
fish_color_comment 4a4a4a --italics
fish_color_selection dddddd --bold --background=2a2a2a
fish_color_search_match 121212 --bold --background=7bd88f
fish_color_operator 5ad4e6
fish_color_escape 9ce5f0
fish_color_autosuggestion 4a4a4a
fish_color_cancel fc618d --reverse
fish_color_cwd 7bd88f
fish_color_cwd_root fc618d
fish_color_host cccccc
fish_color_host_remote fce566
fish_color_user 7bd88f
fish_color_status fc618d
fish_color_valid_path --underline
fish_color_history_current --bold

fish_pager_color_progress 4a4a4a --background=191919
fish_pager_color_background --background=191919
fish_pager_color_prefix 5ad4e6 --bold --underline
fish_pager_color_completion cccccc
fish_pager_color_description aaaaaa --italics
fish_pager_color_selected_background --background=2a2a2a
fish_pager_color_selected_prefix 9ce5f0 --bold --underline --background=2a2a2a
fish_pager_color_selected_completion f1f1f1 --background=2a2a2a
fish_pager_color_selected_description cccccc --background=2a2a2a
fish_pager_color_secondary_background --background=191919
fish_pager_color_secondary_prefix 5ca9ff --background=191919
fish_pager_color_secondary_completion cccccc --background=191919
fish_pager_color_secondary_description 4a4a4a --background=191919
